events {
    worker_connections 1024;
}

http {
    upstream backends {
        server backend1:80;
        server backend2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backends;

            # Cabecera personalizada para identificar qué backend responde
            add_header X-Backend-Server $upstream_addr always;
            add_header X-Proxy "nginx-proxy" always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
